"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ChatChannel = exports.SocketEvent = void 0;
var SocketEvent;
(function (SocketEvent) {
    SocketEvent["CONNECT"] = "connect";
    SocketEvent["DISCONNECT"] = "disconnect";
    SocketEvent["ERROR"] = "error";
    SocketEvent["AUTH_LOGIN"] = "auth:login";
    SocketEvent["AUTH_LOGOUT"] = "auth:logout";
    SocketEvent["AUTH_REGISTER"] = "auth:register";
    SocketEvent["AUTH_SUCCESS"] = "auth:success";
    SocketEvent["AUTH_FAILED"] = "auth:failed";
    SocketEvent["PLAYER_JOIN"] = "player:join";
    SocketEvent["PLAYER_LEAVE"] = "player:leave";
    SocketEvent["PLAYER_MOVE"] = "player:move";
    SocketEvent["PLAYER_UPDATE"] = "player:update";
    SocketEvent["PLAYER_STATS"] = "player:stats";
    SocketEvent["CHAT_MESSAGE"] = "chat:message";
    SocketEvent["CHAT_GLOBAL"] = "chat:global";
    SocketEvent["CHAT_WHISPER"] = "chat:whisper";
    SocketEvent["CHAT_PARTY"] = "chat:party";
    SocketEvent["CHAT_SYSTEM"] = "chat:system";
    SocketEvent["COMBAT_START"] = "combat:start";
    SocketEvent["COMBAT_ACTION"] = "combat:action";
    SocketEvent["COMBAT_RESULT"] = "combat:result";
    SocketEvent["COMBAT_END"] = "combat:end";
    SocketEvent["COMBAT_TURN"] = "combat:turn";
    SocketEvent["ROOM_ENTER"] = "room:enter";
    SocketEvent["ROOM_LEAVE"] = "room:leave";
    SocketEvent["ROOM_UPDATE"] = "room:update";
    SocketEvent["ROOM_PLAYERS"] = "room:players";
    SocketEvent["INVENTORY_UPDATE"] = "inventory:update";
    SocketEvent["INVENTORY_ADD"] = "inventory:add";
    SocketEvent["INVENTORY_REMOVE"] = "inventory:remove";
    SocketEvent["INVENTORY_USE"] = "inventory:use";
    SocketEvent["TRADE_REQUEST"] = "trade:request";
    SocketEvent["TRADE_ACCEPT"] = "trade:accept";
    SocketEvent["TRADE_DECLINE"] = "trade:decline";
    SocketEvent["TRADE_UPDATE"] = "trade:update";
    SocketEvent["TRADE_COMPLETE"] = "trade:complete";
    SocketEvent["SYSTEM_BROADCAST"] = "system:broadcast";
    SocketEvent["SYSTEM_NOTIFICATION"] = "system:notification";
    SocketEvent["SYSTEM_MAINTENANCE"] = "system:maintenance";
})(SocketEvent || (exports.SocketEvent = SocketEvent = {}));
var ChatChannel;
(function (ChatChannel) {
    ChatChannel["GLOBAL"] = "global";
    ChatChannel["LOCAL"] = "local";
    ChatChannel["WHISPER"] = "whisper";
    ChatChannel["PARTY"] = "party";
    ChatChannel["GUILD"] = "guild";
    ChatChannel["SYSTEM"] = "system";
})(ChatChannel || (exports.ChatChannel = ChatChannel = {}));
//# sourceMappingURL=events.types.js.map